### ISSUE TITLE
ERROR TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by francisrod01** [NathanaelA/nativescript-themes#4] opened 2018-06-03 14:34 UTC
I've be learning `eggehead.io` last class about `Use the nativescript-themes plugin to switch app themes on the fly`. 

My `app.component.ts` file:

```ts
import { Component } from "@angular/core";
import { applyTheme } from 'nativescript-themes';

import { setStatusBarColors } from "./utils/status-bar-util";

@Component({
    selector: "ns-app",
    templateUrl: "app.component.html",
})

export class AppComponent {
    private _active = 'app';

    constructor() {
        setStatusBarColors();
    }

    public changeTheme() {
        if (this._active === 'app') {
            this._active = 'blue';
            console.dir(`Change theme to ${this._active} theme`);
            applyTheme(`${this._active}.css`);
        }
        else {
            this._active = 'app';
            console.dir(`Change theme to ${this._active} theme`);
            applyTheme(`${this._active}.css`);
        }
    }
}
```

When I tap the button I receive the compile output:

```
JS: Change theme to blue theme
JS: ERROR TypeError: Cannot read property 'length' of undefined
JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 33603587,
JS:       "rootNodeFlags": 33554435,
JS:       "nodeMatchedQueries": 0,
JS:       "flags": 0,
JS:       "nodes": [
JS:         {
JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,
JS:           "checkIndex": -1,
JS:           "flags": 2,
JS:           "childFlags": 0,
JS:           "directChildFlags": 0,
JS:           "childMatchedQueries": 0,
JS:           "matchedQueries": {},
JS:           "matchedQueryIds": 0,
JS:           "references": {},
JS:           "ngContentIndex": null,
JS:           "childCount": 0,
JS:           "bindings": [],
JS:           "bindingFlags": 8,
JS:           "outputs": [],
JS:           "element": null,
JS:           "provider": null,
JS:           "text": {
JS:             "prefix": "\n"
JS:           },
JS:           "query": null,
JS:           "ngContent": null
JS:         },
JS:         {
JS:           "nodeIndex": 1,
JS:           "parent": null,
JS:           "renderParent": null,
JS:           "bindingIndex": 0,
JS:           "outputIndex"...
```

**Comment by NathanaelA** [comment] 2018-06-04 22:14
This is a duplicate of #3 - However, #3 is now waiting for 
https://github.com/NativeScript/NativeScript/issues/5912  OR  https://github.com/NativeScript/NativeScript/issues/5911 to be fixed...

**Closed as completed by NathanaelA** 2018-06-04 22:14 UTC
